version: "3"

services:
  app:
    build: .
    container_name: node-container
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3333:3333
      - 8080:8080
    restart: always
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: pgsql-container
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: discussions-forum-db
