version: "3"

services:
  app:
    build: .
    container_name: node-container
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3333:3333
      - 8080:8080
    restart: always
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: db-container
    restart: always
    ports:
      # outside-docker:inside-docker
      - 9876:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: forum-db

volumes:
  pgdata:
